# Generated by Django 4.1.6 on 2023-03-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Номер заказа')),
                ('type', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Тип информации: 1-итог,2-товар')),
                ('title', models.CharField(default='Товар', max_length=100, null=True, verbose_name='Наименование продукта')),
                ('qty', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Остатки продукта')),
                ('qty_old', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Остатки продукта')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена продукта')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость продуктов')),
                ('product_id', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Id продукта')),
                ('customer_id', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Id клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('other', 'Разное'), ('smartphones', 'Смартфоны'), ('laptops', 'Ноутбуки'), ('refrigerators', 'Холодильники'), ('TV', 'Телевизоры')], default='other', max_length=20, verbose_name='Категория')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование продукта')),
                ('text', models.TextField(max_length=2000, verbose_name='Описание продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена продукта')),
                ('photo', models.CharField(max_length=200, verbose_name='Изображение продукта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('qty', models.PositiveSmallIntegerField(default=0, verbose_name='Остатки продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя покупателя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон покупателя')),
                ('address', models.CharField(max_length=40, verbose_name='Адрес покупателя')),
                ('products', models.ManyToManyField(blank=True, related_name='customer', to='shop_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(default=0, verbose_name='Тип информации: 1-итог,2-товар')),
                ('title', models.CharField(default='Товар', max_length=100, verbose_name='Наименование продукта')),
                ('qty_prod', models.PositiveSmallIntegerField(default=0, verbose_name='Количество единиц в магазине')),
                ('qty', models.PositiveSmallIntegerField(default=0, verbose_name='Количество единиц в корзине')),
                ('qty_old', models.PositiveSmallIntegerField(default=0, verbose_name='Прежднее количество единиц в корзине')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена продукта')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость продукта')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='basket', to='shop_app.customer', verbose_name='Покупатель')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='basket', to='shop_app.product', verbose_name='Продукт')),
            ],
        ),
    ]
